package edu.depauw.scales.reactive

import java.awt.event.{MouseEvent, MouseMotionListener}

/**
 * Adapter class which interfaces as MouseMotionListener and extends a MouseEventStream to include
 * events generated by mouse motion.
 */
class MouseInputEventStream extends MouseEventStream with MouseMotionListener {
  def mouseDragged (e: MouseEvent) = fire(e)
  def mouseMoved   (e: MouseEvent) = fire(e)
}